/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_fancylab_util_NativePassUtil */

#ifndef _Included_cn_fancylab_util_NativePassUtil
#define _Included_cn_fancylab_util_NativePassUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_fancylab_util_NativePassUtil
 * Method:    encodeNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_fancylab_util_NativePassUtil_encodeNative
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
